# -*- coding: utf-8 -*-
"""Preços memória RAM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W1BbU1FJTj_K8wf93d0svP2a5aqIjs8t
"""

# pip install selenium
# pip install openpyxl

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from openpyxl import Workbook
from openpyxl import load_workbook
from datetime import datetime

urls = ['Link 1', 'Link 2', 'Link 3', ]

driver = webdriver.Chrome()
def pegar_preco():
  elemento = WebDriverWait(driver, 10).until(EC.visibility_of_element_located((By.XPATH, "//h4[contains(text(), 'R$')]")))
  texto_preco = elemento.text
  texto_preco = texto_preco.replace('R$','').replace('.','').replace(',','.').strip()
  return float(texto_preco)


def salva_preco(valor):
  try:
    wb = load_workbook('precos.xlsx')
    planilha = wb.active
  except:
    wb = Workbook()
    planilha = wb.active
    planilha.append(['Data', 'Preço'])

  data_atual = datetime.now().strftime('%Y-%m-%d %H:%M')
  planilha.append([data_atual, valor])
  wb.save('precos.xlsx')

def pegar_ultimo_preco():
  try:
    wb = load_workbook('precos.xlsx')
    planilha = wb.active
    ultima_linha = planilha.max_row
    if ultima_linha <2:
      return None
    ultimo_preco = planilha[f'B{ultima_linha}'].value
    return float(ultimo_preco)
  except:
    return None

def disponibilidade(driver):
  try:
    driver.find_element(By.XPATH, "//*[contains(text(), 'Comprar agora')]")
    return True
  except:
    return False

for url in urls:
  try:
      driver.get(url)
      valor = pegar_preco()
      disponivel = disponibilidade(driver)
      print(f'{url} - R${valor:.2f}')
      if disponivel:
        print('Produto disponível')
      else:
        print('Produto indisponível')

      diferenca = valor - 900

      if valor < 900:
        print(f'O valor baixou R$ {abs(diferenca):.2f}')
      elif valor > 900:
        print(f'O valor subiu R$ {abs(diferenca):.2f}')
      else:
        print('Nada mudou, o valor está igual')

      ultimo = pegar_ultimo_preco()

      if ultimo is not None:
        diferenca = valor - ultimo
        if valor < ultimo:
          print(f'O preço baixou R$ {abs(diferenca):.2f}')
        elif valor > ultimo:
          print(f'O preço subiu R$ {abs(diferenca):.2f}')
        else:
          print('Nada mudou')
      else:
        print('Primeira coleta, sem dados ainda')
      salva_preco (valor)
  except Exception as e:
    print(f'Erro no produto {url}')
driver.quit()

